### PR TITLE
Adds support for right-angled connections

### PR DESCRIPTION
**Pull request by pmill**
This pull request adds support for right-angled connections, e.g.:

```
editor.use(ConnectionPlugin, { renderType: ConnectionPlugin.renderTypeRightAngled});
```

### CODE REVIEW

**Comment by Ni55aN** [comment]
Hmm.. I think it's better to make such a functional as a separate module, not interweaving it with the current functionality. I'll try to do this next week, I'll think about such a concept as friendly plug-ins (one plug-in will expand/call another)

**Comment by pmill** [comment]
I did also make a separate plugin for this that I'm using myself, up to you if you want to use it though.

https://github.com/pmill/rete-connection-plugin

**Comment by Ni55aN** [comment]
I mean the functionality in the form of another plugin that will complement the current one. So far, the svg-path-generator dependency will be installed even when no right-angled connections are needed

**Comment by Ni55aN** [comment]
I have implemented Vue.js render plugin and now I'm interested in integrating this feature. Do you have any changes or suggestions? 

The connection plugin will have interfaces for extending it to some functions that will be connected to it optionally in the form of other plug-ins.

**Comment by Ni55aN** [comment]
This feature has been implemented in [connection-path-plugin](https://github.com/retejs/connection-path-plugin)

**Comment by Ni55aN** [comment]
Example: https://codepen.io/Ni55aN/pen/ZMdPea

**Pull request closed without merging**
